"""Accessibility + theme guard for inline <svg> diagrams in long-form pages.

Why this file exists
--------------------
On 2026-09-09 an a11y pass raised `--faint` to clear 4.5:1 on all three
surfaces, guarded by tests/test_a11y_contrast.py. That guard reads
`css/style.css` and `index.html` ONLY, and only for the `--faint` token --
it cannot see a color written into an SVG `fill=` / `stroke=` attribute in
an article page. Inline diagrams were introduced the same day, which opened
exactly that blind spot: a hardcoded hex inside a diagram is invisible to
every existing check, and an unlabelled <svg> is a silent regression of the
a11y pass rather than a loud one.

So this file guards the diagrams themselves. The rule it enforces is that a
diagram must carry its meaning in text as well as in pixels, and must take
its colors from the palette rather than restating them.

SCOPE (stated with the pattern, deliberately)
---------------------------------------------
IN scope:  <svg> elements in articles/*.html and case-studies/*.html --
           the long-form prose pages that share css/style.css and its
           blue-accent palette.
OUT of scope, on purpose and not by omission:
  * index.html -- carries its own inline <style> and a DIFFERENT palette
    (teal accent #5eead4), so `var(--accent)` would not mean the same thing
    there. See tests/test_a11y_contrast.py's module docstring for the same
    two-palette split.
  * 404.html, managed-watch.html, scoreboard.html -- not long-form prose;
    scoreboard.html in particular is generated by
    scripts/generate-scoreboard.mjs, so a rule here would be enforced
    against the wrong artifact (the generator, not the page).
  * scripts/og-card.html -- a render SOURCE for a 1200x630 screenshot, not
    a page anyone navigates to, and deliberately self-contained.

DECORATIVE SVG EXEMPTION
------------------------
An <svg aria-hidden="true"> is decorative and is exempt from the labelling
rules (R1/R2) -- the same exemption index.html's `.deco` element already
relies on. The exemption is asserted explicitly in the positive controls
below so that it is a tested carve-out rather than an untested loophole.
It is NOT exempt from R3/R5/R6: a decorative diagram still must not force
horizontal scroll or hardcode a hex.
"""

from __future__ import annotations

import re
from html.parser import HTMLParser
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent

IN_SCOPE_GLOBS = ("articles/*.html", "case-studies/*.html")

# A six- or three-digit hex literal. Colors must come from the palette
# (var(--token)), from currentColor, or be absent (none) -- never restated.
HEX_LITERAL_RE = re.compile(r"#[0-9a-fA-F]{3,8}\b")

# Hex is not the only way to hardcode a color. A named color (white, black)
# or an rgb()/hsl() function bypasses a hex-only check completely, so the
# paint attributes are ALLOWLISTED by shape rather than denylisted by
# pattern: state what is permitted, and everything else is a finding.
PAINT_ATTR_RE = re.compile(
    r"\b(fill|stroke|stop-color|color|flood-color|lighting-color)\s*=\s*\"([^\"]*)\"",
    re.I,
)
ALLOWED_PAINT = re.compile(
    r"^\s*(none|transparent|inherit|currentColor|var\(\s*--[A-Za-z0-9_-]+\s*(,[^)]*)?\))\s*$",
    re.I,
)

# Standing house rule: no em-dashes in public-facing copy.
EM_DASH = "—"

SVG_BLOCK_RE = re.compile(r"<svg\b.*?</svg>", re.S | re.I)
FIGURE_BLOCK_RE = re.compile(r"<figure\b.*?</figure>", re.S | re.I)


def in_scope_pages() -> list[Path]:
    pages: list[Path] = []
    for glob in IN_SCOPE_GLOBS:
        pages.extend(sorted(REPO_ROOT.glob(glob)))
    return pages


class _FigureParser(HTMLParser):
    """Collects every <svg> with its attrs, its <title>s, and the
    <figcaption> text of the <figure> enclosing it (if any).

    Written against html.parser (stdlib) rather than a regex because the
    enclosing-figure question is a nesting question, and this repo has no
    package.json / node_modules and adds no dependencies.
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.svgs: list[dict] = []
        self._stack: list[str] = []
        self._svg_depth: int | None = None
        self._current: dict | None = None
        self._figure_depth: int | None = None
        self._figcaption_text: list[str] = []
        self._figure_svg_start = 0
        self._in_figcaption = False
        self._in_title = False
        self.max_svg_nesting = 0

    def handle_starttag(self, tag, attrs):
        tag = tag.lower()
        attrd = {k.lower(): (v or "") for k, v in attrs}
        self._stack.append(tag)
        if tag == "figure":
            self._figure_depth = len(self._stack)
            self._figcaption_text = []
            # Only the <svg>s opened from here on belong to THIS figure.
            # Without this marker, a second figure's caption would be
            # assigned to an earlier figure's uncaptioned svg, and an empty
            # first caption would pass. That is a false negative, which is
            # the one failure mode a guard must not have.
            self._figure_svg_start = len(self.svgs)
        elif tag == "figcaption":
            self._in_figcaption = True
        elif tag == "svg":
            if self._current is not None:
                # Nested <svg>. This parser reports it so the caller can
                # declare the run indeterminate rather than emit a finding
                # against markup it cannot model.
                self.max_svg_nesting = max(self.max_svg_nesting, 2)
            self._svg_depth = len(self._stack)
            self._current = {
                "attrs": attrd,
                "titles": [],
                "title_ids": [],
                "in_figure": self._figure_depth is not None,
                "figcaption": "",
            }
        elif tag == "title" and self._current is not None:
            self._in_title = True
            self._current["titles"].append("")
            self._current["title_ids"].append(attrd.get("id", ""))

    def handle_endtag(self, tag):
        tag = tag.lower()
        if tag == "figcaption":
            self._in_figcaption = False
        elif tag == "title":
            self._in_title = False
        elif tag == "svg" and self._current is not None:
            self.svgs.append(self._current)
            self._current = None
            self._svg_depth = None
        elif tag == "figure":
            caption = "".join(self._figcaption_text).strip()
            for svg in self.svgs[self._figure_svg_start:]:
                if svg["in_figure"]:
                    svg["figcaption"] = caption
            self._figure_depth = None
            self._figure_svg_start = len(self.svgs)
        while self._stack:
            popped = self._stack.pop()
            if popped == tag:
                break

    def handle_data(self, data):
        if self._in_title and self._current is not None:
            self._current["titles"][-1] += data
        if self._in_figcaption:
            self._figcaption_text.append(data)


def parse_svgs(source: str) -> tuple[list[dict], int]:
    p = _FigureParser()
    p.feed(source)
    p.close()
    return p.svgs, p.max_svg_nesting


def check_svg_source(source: str) -> list[str]:
    """Return a list of violation strings. Empty list == clean.

    This is the single function both the real pages and the positive
    controls run through, so a control cannot pass against a different
    code path than the one guarding the repo.
    """
    problems: list[str] = []
    svgs, nesting = parse_svgs(source)

    raw_blocks = SVG_BLOCK_RE.findall(source)
    if nesting >= 2 or len(raw_blocks) != len(svgs):
        # Cannot discriminate -- report indeterminate, never a finding.
        return [
            "INDETERMINATE: nested or unbalanced <svg> markup "
            f"(parser saw {len(svgs)}, regex saw {len(raw_blocks)}); "
            "this guard cannot model it, so it refuses to judge it"
        ]

    for i, (svg, raw) in enumerate(zip(svgs, raw_blocks)):
        attrs = svg["attrs"]
        label = f"svg#{i}"
        decorative = attrs.get("aria-hidden", "").lower() == "true"

        # R1/R2 -- an informative diagram must expose its meaning as text.
        if not decorative:
            if attrs.get("role", "").lower() != "img":
                problems.append(f'{label}: missing role="img"')

            labelled_by = attrs.get("aria-labelledby", "").strip()
            aria_label = attrs.get("aria-label", "").strip()
            titles = [t.strip() for t in svg["titles"]]
            # id -> text, for the titles that carry an id at all.
            by_id = {
                i_: t
                for i_, t in zip(svg["title_ids"], titles)
                if i_
            }

            if not any(titles):
                problems.append(f"{label}: missing a non-empty <title> element")
            if not labelled_by and not aria_label:
                problems.append(
                    f"{label}: needs aria-labelledby (pointing at its <title>) "
                    "or aria-label"
                )
            if labelled_by:
                refs = labelled_by.split()
                missing = [t for t in refs if t not in by_id]
                if missing:
                    problems.append(
                        f"{label}: aria-labelledby references {missing} but no "
                        f"<title> carries that id (title ids: {sorted(by_id)})"
                    )
                # The accessible name is built from the REFERENCED nodes only.
                # Checking "some <title> somewhere is non-empty" would let an
                # SVG whose referenced title is blank pass on the strength of
                # an unreferenced one -- a false negative.
                blank = [t for t in refs if t in by_id and not by_id[t]]
                if blank:
                    problems.append(
                        f"{label}: aria-labelledby points at {blank}, whose "
                        "<title> text is empty, so the accessible name is blank"
                    )

            # R4 -- a content figure needs a visible caption too. The
            # accessible name names the diagram; the caption explains it.
            if not svg["in_figure"]:
                problems.append(f"{label}: not wrapped in a <figure>")
            elif not svg["figcaption"].strip():
                problems.append(f"{label}: enclosing <figure> has no <figcaption> text")

        # R3 -- responsive: viewBox, and no fixed pixel width/height that
        # would force horizontal scroll on a narrow viewport.
        if "viewbox" not in attrs:
            problems.append(f"{label}: missing viewBox")
        for dim in ("width", "height"):
            if dim in attrs:
                problems.append(
                    f"{label}: has a fixed {dim}=\"{attrs[dim]}\" on the root "
                    "<svg>; size it with viewBox + CSS instead"
                )

        # R5 -- colors come from the palette, not restated literals.
        hexes = sorted(set(HEX_LITERAL_RE.findall(raw)))
        if hexes:
            problems.append(
                f"{label}: hardcoded color literal(s) {hexes}; use var(--token) "
                "or currentColor so the diagram tracks the palette"
            )
        bad_paint = sorted(
            {
                f"{a}=\"{v}\""
                for a, v in PAINT_ATTR_RE.findall(raw)
                if not ALLOWED_PAINT.match(v)
            }
        )
        if bad_paint:
            problems.append(
                f"{label}: paint attribute(s) {bad_paint} are not a palette "
                "token; allowed: var(--token), currentColor, none, transparent, "
                "inherit"
            )

        # R6 -- house copy rule, applied to diagram text too.
        if EM_DASH in raw:
            problems.append(f"{label}: contains an em-dash")

    return problems


def check_figure_copy(source: str) -> list[str]:
    """Em-dash guard across the whole <figure>, not just the <svg>."""
    problems = []
    for i, block in enumerate(FIGURE_BLOCK_RE.findall(source)):
        if EM_DASH in block:
            problems.append(f"figure#{i}: contains an em-dash")
    return problems


# --------------------------------------------------------------------------
# The real repo
# --------------------------------------------------------------------------


@pytest.mark.parametrize("page", in_scope_pages(), ids=lambda p: p.name)
def test_inline_svgs_are_accessible_and_themed(page: Path) -> None:
    source = page.read_text(encoding="utf-8")
    problems = check_svg_source(source) + check_figure_copy(source)
    assert not problems, f"{page.relative_to(REPO_ROOT)}:\n  " + "\n  ".join(problems)


def test_scope_is_non_empty() -> None:
    """A guard that matches nothing is satisfied by silence.

    If the globs ever stop resolving, this fails loudly instead of the
    suite going quietly green on zero pages.
    """
    pages = in_scope_pages()
    assert len(pages) >= 20, f"expected the article/case-study corpus, got {len(pages)}"


# --------------------------------------------------------------------------
# Positive controls -- the checker must FIRE on known-bad and STAY SILENT
# on known-good. A check never shown to fire is not a check.
# --------------------------------------------------------------------------

GOOD = """
<figure class="diagram">
  <svg role="img" aria-labelledby="d1t" viewBox="0 0 100 40">
    <title id="d1t">A one-line description of the mechanism.</title>
    <rect x="1" y="1" width="20" height="10" fill="var(--card)"
          stroke="var(--muted)"/>
    <text x="4" y="9" fill="var(--text)">ok</text>
  </svg>
  <figcaption>A caption that stands on its own.</figcaption>
</figure>
"""

GOOD_DECORATIVE = """
<svg aria-hidden="true" viewBox="0 0 10 10">
  <circle cx="5" cy="5" r="4" fill="var(--border)"/>
</svg>
"""

BAD_CASES = {
    "no_role": GOOD.replace('role="img" ', ""),
    "no_title": GOOD.replace('<title id="d1t">A one-line description of the mechanism.</title>', ""),
    "empty_title": GOOD.replace("A one-line description of the mechanism.", "   "),
    "no_labelledby": GOOD.replace('aria-labelledby="d1t" ', ""),
    "dangling_labelledby": GOOD.replace('aria-labelledby="d1t"', 'aria-labelledby="nope"'),
    "no_figure": GOOD.replace("<figure class=\"diagram\">", "").replace("</figure>", ""),
    "no_figcaption": GOOD.replace(
        "<figcaption>A caption that stands on its own.</figcaption>", ""
    ),
    "empty_figcaption": GOOD.replace("A caption that stands on its own.", "  "),
    "no_viewbox": GOOD.replace('viewBox="0 0 100 40"', ""),
    "fixed_width": GOOD.replace('viewBox="0 0 100 40"', 'viewBox="0 0 100 40" width="900"'),
    "fixed_height": GOOD.replace('viewBox="0 0 100 40"', 'viewBox="0 0 100 40" height="480"'),
    "hardcoded_hex": GOOD.replace('fill="var(--text)"', 'fill="#e8edf6"'),
    "em_dash_in_title": GOOD.replace("mechanism.", "mechanism — really."),
    # Non-hex hardcoded colors: a hex-only guard would wave these through.
    "named_color_fill": GOOD.replace('fill="var(--text)"', 'fill="white"'),
    "named_color_stroke": GOOD.replace('stroke="var(--muted)"', 'stroke="black"'),
    "rgb_function": GOOD.replace('fill="var(--text)"', 'fill="rgb(231,236,243)"'),
    "hsl_function": GOOD.replace('fill="var(--card)"', 'fill="hsl(220 30% 12%)"'),
    # The em-dash lives only in the caption, outside the <svg> block.
    "em_dash_in_figcaption_only": GOOD.replace(
        "A caption that stands on its own.", "A caption — with an em-dash."
    ),
}


def test_positive_control_good_markup_is_silent() -> None:
    assert check_svg_source(GOOD) == []
    assert check_figure_copy(GOOD) == []


def test_positive_control_decorative_svg_is_exempt_from_labelling() -> None:
    """The aria-hidden carve-out is real: no role/title/figure demanded..."""
    assert check_svg_source(GOOD_DECORATIVE) == []


def test_positive_control_decorative_svg_still_guarded_on_the_rest() -> None:
    """...but a decorative diagram is NOT exempt from viewBox/hex/em-dash."""
    bad = GOOD_DECORATIVE.replace('viewBox="0 0 10 10"', 'width="800"')
    problems = check_svg_source(bad)
    assert any("viewBox" in p for p in problems), problems
    assert any("fixed width" in p for p in problems), problems

    hexed = GOOD_DECORATIVE.replace('fill="var(--border)"', 'fill="#233048"')
    assert any("hardcoded color" in p for p in check_svg_source(hexed))


@pytest.mark.parametrize("name", sorted(BAD_CASES))
def test_positive_control_bad_markup_fires(name: str) -> None:
    source = BAD_CASES[name]
    problems = check_svg_source(source) + check_figure_copy(source)
    assert problems, f"checker stayed silent on known-bad case {name!r}"


def test_positive_control_second_figures_caption_cannot_rescue_the_first() -> None:
    """A later figure's caption must not be credited to an earlier svg.

    The parser assigns captions per figure. If it instead assigned the
    first empty caption it could find, this two-figure page would pass
    with figure #1 uncaptioned. That is a false negative, so it gets its
    own control rather than relying on the single-figure cases.
    """
    empty_first = GOOD.replace("A caption that stands on its own.", "  ")
    two = empty_first + GOOD
    problems = check_svg_source(two)
    assert any("no <figcaption> text" in p for p in problems), problems
    # ...and the well-formed second figure must not be blamed for it.
    assert sum("no <figcaption> text" in p for p in problems) == 1, problems


def test_positive_control_two_good_figures_stay_silent() -> None:
    assert check_svg_source(GOOD + GOOD) == []


def test_positive_control_unreferenced_title_cannot_supply_the_name() -> None:
    """An empty REFERENCED title is not rescued by a populated sibling.

    The accessible name comes from the node aria-labelledby points at. A
    guard that only asked "is some <title> non-empty" would pass this SVG
    while a screen reader announced nothing.
    """
    two_titles = GOOD.replace(
        '<title id="d1t">A one-line description of the mechanism.</title>',
        '<title id="d1t"></title>'
        '<title id="other">Text on a title nobody references.</title>',
    )
    problems = check_svg_source(two_titles)
    assert any("accessible name is blank" in p for p in problems), problems


def test_positive_control_em_dash_in_caption_only_is_caught() -> None:
    src = BAD_CASES["em_dash_in_figcaption_only"]
    # Clean inside the <svg>...
    assert not any("em-dash" in p for p in check_svg_source(src))
    # ...and still caught at the figure level.
    assert any("em-dash" in p for p in check_figure_copy(src))


def test_indeterminate_on_nested_svg_rather_than_a_finding() -> None:
    """A check that cannot discriminate must say so, not emit a verdict."""
    nested = """
    <figure><svg role="img" aria-labelledby="a" viewBox="0 0 10 10">
      <title id="a">outer</title><svg viewBox="0 0 5 5"></svg>
    </svg><figcaption>c</figcaption></figure>
    """
    problems = check_svg_source(nested)
    assert len(problems) == 1
    assert problems[0].startswith("INDETERMINATE")
