"""Tests for scripts/check_beacon_coverage.py.

Uses only temp fixtures (tmp_path) -- never touches the real site content files
(index.html, case-studies/*.html, scripts/generate-scoreboard.mjs), per the
lane contract's rule that tests must not mutate real site files.

Enforces docs/INSTRUMENTATION-SETUP.md's "Coverage rule" (lines 38-64): every
user-facing *.html page carries EXACTLY ONE data-goatcounter tag. Zero fails
(missing beacon). Two fails (duplicate beacon, double-counts views). The
producer/consumer parity case (scoreboard.html vs its generator template) is
the one a naive scan-the-output-only check gets wrong -- see
test_generator_template_losing_beacon_fails_even_when_output_still_has_one.
"""

import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

import check_beacon_coverage as cbc  # noqa: E402

BEACON_TAG = (
    '<script data-goatcounter="https://jaimenbell.goatcounter.com/count" '
    'async src="//gc.zgo.at/count.js"></script>'
)


def write(tmp_path: Path, name: str, content: str) -> Path:
    p = tmp_path / name
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return p


# ---------------------------------------------------------------------------
# POSITIVE CONTROL, direction 1: the check FIRES on known-bad input.
# ---------------------------------------------------------------------------


def test_page_with_tag_stripped_fails(tmp_path):
    """A page with the beacon tag missing entirely is a coverage gap -- must FAIL."""
    site = tmp_path / "site"
    write(site, "index.html", f"<html><head></head><body>no beacon here</body></html>\n")

    exit_code = cbc.run(root=site, target_patterns=["*.html"], generated_pairs={})

    assert exit_code == 2


def test_page_with_duplicate_tag_fails(tmp_path):
    """A page carrying the tag TWICE double-counts pageviews -- must FAIL, not
    silently pass because 'at least one' tag is present."""
    site = tmp_path / "site"
    write(
        site, "index.html",
        f"<html><head>{BEACON_TAG}\n{BEACON_TAG}</head><body>x</body></html>\n",
    )

    exit_code = cbc.run(root=site, target_patterns=["*.html"], generated_pairs={})

    assert exit_code == 2


def test_generator_template_losing_beacon_fails_even_when_output_still_has_one(tmp_path):
    """THE PARITY CASE. scoreboard.html is fully GENERATED by
    generate-scoreboard.mjs; its beacon lives in the generator's <head>
    template, not only the output file. A check that scans only the output
    file goes GREEN while the generator loses its beacon -- and the very
    next `node scripts/generate-scoreboard.mjs` run silently reverts the
    output back to beacon-less. This is the case a naive scan-the-output-only
    check gets wrong; this checker must catch it by scanning BOTH sides."""
    site = tmp_path / "site"
    write(site, "scoreboard.html", f"<html><head>{BEACON_TAG}</head><body>x</body></html>\n")
    write(site, "scripts/generate-scoreboard.mjs", "const html = `<head></head>`;\n")

    exit_code = cbc.run(
        root=site,
        target_patterns=["scoreboard.html"],
        generated_pairs={"scoreboard.html": "scripts/generate-scoreboard.mjs"},
    )

    assert exit_code == 2, (
        "the generator template lost its beacon -- this MUST fail even though "
        "the (soon to be silently reverted) output file still carries one"
    )


def test_generator_template_with_duplicate_beacon_fails(tmp_path):
    """Parity check applies the same exactly-one rule to the generator side,
    not just missing/present."""
    site = tmp_path / "site"
    write(site, "scoreboard.html", f"<html><head>{BEACON_TAG}</head><body>x</body></html>\n")
    write(
        site, "scripts/generate-scoreboard.mjs",
        f"const html = `<head>{BEACON_TAG}\n{BEACON_TAG}</head>`;\n",
    )

    exit_code = cbc.run(
        root=site,
        target_patterns=["scoreboard.html"],
        generated_pairs={"scoreboard.html": "scripts/generate-scoreboard.mjs"},
    )

    assert exit_code == 2


# ---------------------------------------------------------------------------
# POSITIVE CONTROL, direction 2: the check STAYS SILENT on known-good input.
# ---------------------------------------------------------------------------


def test_known_good_tree_mirroring_real_26_of_26_state_stays_silent(tmp_path):
    """A tree shaped like the real repo's current coverage state (every
    user-facing page carrying exactly one tag, generator template carrying
    exactly one tag too) must pass clean -- a check that cannot stay silent
    on good input is as broken as one that cannot fire on bad input."""
    site = tmp_path / "site"
    pages = [
        "index.html", "404.html", "managed-watch.html", "scoreboard.html",
        "articles/build-custom-mcp-server.html",
        "case-studies/mcp-factory.html",
        "case-studies/mcp-security-scanner.html",
    ]
    for p in pages:
        write(site, p, f"<html><head>{BEACON_TAG}</head><body>content</body></html>\n")
    write(
        site, "scripts/generate-scoreboard.mjs",
        f"const html = `<head>{BEACON_TAG}</head>`;\n",
    )

    exit_code = cbc.run(
        root=site,
        target_patterns=["404.html", "index.html", "managed-watch.html",
                          "scoreboard.html", "articles/*.html", "case-studies/*.html"],
        generated_pairs={"scoreboard.html": "scripts/generate-scoreboard.mjs"},
    )

    assert exit_code == 0


def test_excluded_og_card_template_with_no_beacon_does_not_fail(tmp_path):
    """scripts/og-card.html is a documented exclusion (generator template,
    never served to a visitor) -- it must not even be in the scanned
    population, so it carrying zero tags must never fail the gate."""
    site = tmp_path / "site"
    write(site, "index.html", f"<html><head>{BEACON_TAG}</head><body>x</body></html>\n")
    write(site, "scripts/og-card.html", "<html><head></head><body>no beacon, by design</body></html>\n")

    exit_code = cbc.run(
        root=site,
        target_patterns=["index.html"],  # explicit glob list never includes scripts/*.html
        generated_pairs={},
    )

    assert exit_code == 0


# ---------------------------------------------------------------------------
# Unit-level coverage of the building blocks.
# ---------------------------------------------------------------------------


def test_count_beacon_tags_zero():
    assert cbc.count_beacon_tags("<html><head></head></html>") == 0


def test_count_beacon_tags_one():
    assert cbc.count_beacon_tags(f"<html><head>{BEACON_TAG}</head></html>") == 1


def test_count_beacon_tags_two():
    assert cbc.count_beacon_tags(f"<head>{BEACON_TAG}\n{BEACON_TAG}</head>") == 2


def test_resolve_targets_only_matches_explicit_globs_not_implicit_walk(tmp_path):
    """Population is an explicit glob list (imitating check_proof_numbers.py's
    DEFAULT_TARGET_GLOBS idiom), never an implicit directory walk -- a page
    dropped somewhere the globs don't name is simply out of scope, not
    silently swept in. Here scripts/og-card.html and a nested throwaway
    worktree copy are both present on disk but excluded by the glob list."""
    site = tmp_path / "site"
    write(site, "index.html", "a")
    write(site, "scripts/og-card.html", "b")
    write(site, ".claude/worktrees/foo/index.html", "c")

    targets = cbc.resolve_targets(site, ["index.html"])

    assert [t.name for t in targets] == ["index.html"]
    assert all(".claude" not in str(t) for t in targets)
    assert all("og-card" not in str(t) for t in targets)


def test_finding_format_names_file_and_reason_for_missing(tmp_path):
    site = tmp_path / "site"
    p = write(site, "index.html", "<html><head></head></html>\n")
    finding = cbc.check_file(p)
    assert finding is not None
    rendered = finding.format()
    assert "index.html" in rendered
    assert "0" in rendered


def test_finding_format_names_file_and_reason_for_duplicate(tmp_path):
    site = tmp_path / "site"
    p = write(site, "index.html", f"<head>{BEACON_TAG}\n{BEACON_TAG}</head>\n")
    finding = cbc.check_file(p)
    assert finding is not None
    rendered = finding.format()
    assert "index.html" in rendered
    assert "2" in rendered


def test_check_file_returns_none_when_exactly_one_tag(tmp_path):
    site = tmp_path / "site"
    p = write(site, "index.html", f"<head>{BEACON_TAG}</head>\n")
    assert cbc.check_file(p) is None


def test_missing_generator_file_fails_rather_than_silently_skipping(tmp_path):
    """If the named generator script does not exist at all, that is a real
    parity break (the pairing itself is broken), not a reason to silently
    skip the check."""
    site = tmp_path / "site"
    write(site, "scoreboard.html", f"<html><head>{BEACON_TAG}</head></html>\n")
    # scripts/generate-scoreboard.mjs deliberately not created.

    exit_code = cbc.run(
        root=site,
        target_patterns=["scoreboard.html"],
        generated_pairs={"scoreboard.html": "scripts/generate-scoreboard.mjs"},
    )

    assert exit_code == 2


# ---------------------------------------------------------------------------
# Exit-code contract: 0 clean, 2 coverage violated, other non-zero = gate fault.
# ---------------------------------------------------------------------------


def test_run_end_to_end_exit_codes(tmp_path):
    clean_dir = tmp_path / "clean"
    write(clean_dir, "index.html", f"<head>{BEACON_TAG}</head>\n")
    assert cbc.run(root=clean_dir, target_patterns=["*.html"], generated_pairs={}) == 0

    stale_dir = tmp_path / "stale"
    write(stale_dir, "index.html", "<head></head>\n")
    assert cbc.run(root=stale_dir, target_patterns=["*.html"], generated_pairs={}) == 2


def test_main_crash_path_reports_nonzero_not_a_verdict_code(tmp_path, monkeypatch):
    """An unhandled exception inside the gate itself (a fault, not a verdict)
    must exit non-zero but distinct from the checker's own verdict path --
    exercised here by pointing at a root that does not exist, which raises
    rather than quietly resolving to zero targets in a broken state."""
    def _boom(*a, **kw):
        raise RuntimeError("simulated gate fault")

    monkeypatch.setattr(cbc, "resolve_targets", _boom)
    exit_code = cbc.main([])
    assert exit_code not in (0, 2)


# ---------------------------------------------------------------------------
# Hook wiring: the real .githooks/pre-commit, exercised end-to-end.
# ---------------------------------------------------------------------------


def _bash_path() -> str:
    """Return the bash GIT ITSELF uses to run hooks -- mirrors
    test_check_proof_numbers.py's _bash_path() exactly (same WSL-launcher
    trap: resolving via `shutil.which` can find the WindowsApps WSL launcher
    instead of Git's bundled bash, which git never actually uses)."""
    if sys.platform == "win32":
        try:
            exec_path = subprocess.run(
                ["git", "--exec-path"], capture_output=True, text=True, check=True,
            ).stdout.strip()
        except (OSError, subprocess.CalledProcessError):  # pragma: no cover
            exec_path = ""
        if exec_path:
            base = Path(exec_path)
            for parent in [base, *base.parents]:
                for rel in ("bin/bash.exe", "usr/bin/bash.exe"):
                    candidate = parent / rel
                    if candidate.is_file():
                        return str(candidate)
        pytest.skip("git's bundled bash not found -- cannot exercise the shell hook")
    path = shutil.which("bash")
    if path is None:
        pytest.skip("bash not found on PATH -- cannot exercise the shell hook end-to-end")
    return path


def _build_temp_hook_repo(tmp_path: Path, index_html_text: str,
                           scoreboard_html_text: str | None = None,
                           generator_mjs_text: str | None = None) -> Path:
    """Build a minimal git repo with the REAL .githooks/pre-commit and the
    REAL scripts/check_proof_numbers.py + scripts/check_beacon_coverage.py
    wired up, so the hook-wiring change is exercised end-to-end. Never
    touches the real repo's checkout. A trivially-clean proof-manifest.toml
    is included so the proof-numbers gate (which runs first) never blocks
    these beacon-focused fixtures."""
    repo = tmp_path / "hookrepo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=repo, check=True)

    (repo / "scripts").mkdir()
    shutil.copy2(REPO_ROOT / "scripts" / "check_proof_numbers.py", repo / "scripts" / "check_proof_numbers.py")
    shutil.copy2(REPO_ROOT / "scripts" / "check_beacon_coverage.py", repo / "scripts" / "check_beacon_coverage.py")
    (repo / ".githooks").mkdir()
    shutil.copy2(REPO_ROOT / ".githooks" / "pre-commit", repo / ".githooks" / "pre-commit")

    # Empty manifest + no trigger words in index.html -- the proof-numbers
    # gate has nothing to scan/associate and passes clean.
    (repo / "proof-manifest.toml").write_text("", encoding="utf-8", newline="\n")
    (repo / "index.html").write_text(index_html_text, encoding="utf-8", newline="\n")
    if scoreboard_html_text is not None:
        (repo / "scoreboard.html").write_text(scoreboard_html_text, encoding="utf-8", newline="\n")
    if generator_mjs_text is not None:
        (repo / "scripts" / "generate-scoreboard.mjs").write_text(
            generator_mjs_text, encoding="utf-8", newline="\n"
        )
    return repo


def test_hook_blocks_commit_when_beacon_missing(tmp_path):
    """The real pre-commit hook, run end-to-end, blocks a commit whose
    index.html has lost its beacon tag."""
    bash = _bash_path()
    repo = _build_temp_hook_repo(tmp_path, index_html_text="<head></head>\n")

    result = subprocess.run([bash, ".githooks/pre-commit"], cwd=repo, capture_output=True, text=True)

    assert result.returncode == 2, f"{result.stdout}\n{result.stderr}"
    assert "BLOCKED" in result.stdout
    assert "Traceback" not in result.stderr


def test_hook_allows_clean_commit_with_beacon_coverage_ok(tmp_path):
    """Sanity companion: the same real hook, run against a fixture where
    every scanned page (and the scoreboard generator template) carries
    exactly one beacon, exits 0 and never prints a BLOCKED message."""
    bash = _bash_path()
    repo = _build_temp_hook_repo(
        tmp_path,
        index_html_text=f"<head>{BEACON_TAG}</head>\n",
        scoreboard_html_text=f"<head>{BEACON_TAG}</head>\n",
        generator_mjs_text=f"const html = `<head>{BEACON_TAG}</head>`;\n",
    )

    result = subprocess.run([bash, ".githooks/pre-commit"], cwd=repo, capture_output=True, text=True)

    assert result.returncode == 0, f"{result.stdout}\n{result.stderr}"
    assert "BLOCKED" not in result.stdout


def test_hook_reports_beacon_gate_fault_as_cannot_run_not_a_verdict(tmp_path):
    """A crashed beacon checker must be reported as CANNOT RUN, never
    misreported as a coverage verdict -- mirrors the proof-numbers hook's
    existing crash-vs-verdict distinction."""
    bash = _bash_path()
    repo = _build_temp_hook_repo(tmp_path, index_html_text=f"<head>{BEACON_TAG}</head>\n")
    (repo / "scripts" / "check_beacon_coverage.py").write_text(
        "import definitely_not_a_real_module_xyz\n", encoding="utf-8", newline="\n"
    )

    result = subprocess.run([bash, ".githooks/pre-commit"], cwd=repo, capture_output=True, text=True)

    assert result.returncode != 0
    assert "CANNOT RUN" in result.stdout
    assert "BLOCKED" not in result.stdout


# ---------------------------------------------------------------------------
# The gate's OWN blind spot: a page that is neither in scope nor excluded.
#
# DEFAULT_TARGET_GLOBS names the top-level pages LITERALLY, so before
# find_unclassified_pages() existed a newly added root-level page was out of
# scope BY OMISSION -- the gate printed "OK (26 page(s) checked)" and exited 0
# with an uninstrumented page sitting in the tree. Verified adversarially
# against the real repo on 2026-08-20 before the fix.
#
# That is the same shape as the original 16-of-26 incident: pages landed on one
# branch, instrumentation on another, nothing reconciled them. The rule in
# docs/INSTRUMENTATION-SETUP.md is "every user-facing .html page", not "the
# pages someone remembered to list" -- so being unlisted must not read as being
# exempt.
# ---------------------------------------------------------------------------


def test_unclassified_page_FIRES_even_though_it_is_outside_the_globs(tmp_path):
    """The regression guard for the gate's own blind spot: a new top-level page
    that no glob covers and no exclusion names must FAIL, not pass silently."""
    site = tmp_path / "site"
    write(site, "index.html", f"<html><head>{BEACON_TAG}</head><body>ok</body></html>\n")
    write(site, "pricing.html", "<html><head></head><body>brand new page</body></html>\n")

    exit_code = cbc.run(
        root=site,
        target_patterns=["index.html"],
        generated_pairs={},
    )

    assert exit_code == 2, (
        "an unlisted *.html page must FAIL as unclassified -- if this passes, "
        "the gate has regressed to enforcing a hardcoded list instead of the "
        "documented 'every user-facing page' rule"
    )


def test_unclassified_page_fires_even_when_it_DOES_carry_a_beacon(tmp_path):
    """Classification is the point, not the beacon. A page nobody classified is
    a hole in the scope even when it happens to be instrumented today -- the
    next edit to it has no guard."""
    site = tmp_path / "site"
    write(site, "index.html", f"<html><head>{BEACON_TAG}</head><body>ok</body></html>\n")
    write(site, "pricing.html", f"<html><head>{BEACON_TAG}</head><body>ok</body></html>\n")

    assert cbc.run(root=site, target_patterns=["index.html"], generated_pairs={}) == 2


def test_explicitly_excluded_page_STAYS_SILENT(tmp_path):
    """Direction 2 of the control: a page named in the exclusion list is exempt
    and must NOT fail, even carrying zero beacons -- this is what keeps the
    orphan check from being a permanent false positive on og-card.html."""
    site = tmp_path / "site"
    write(site, "index.html", f"<html><head>{BEACON_TAG}</head><body>ok</body></html>\n")
    write(site, "scripts/og-card.html", "<html><body>generator template</body></html>\n")

    findings = cbc.find_unclassified_pages(
        site, ["index.html"], excluded=["scripts/og-card.html"]
    )

    assert findings == []


def test_non_site_directories_are_not_scanned_for_orphans(tmp_path):
    """.claude/worktrees/** is throwaway, not the deployed site. Scanning it
    would make the gate fire on every worktree -- a permanent false positive,
    which trains people to ignore the whole tool."""
    site = tmp_path / "site"
    write(site, "index.html", f"<html><head>{BEACON_TAG}</head><body>ok</body></html>\n")
    write(site, ".claude/worktrees/scratch/index.html", "<html><body>throwaway</body></html>\n")

    assert cbc.find_unclassified_pages(site, ["index.html"]) == []
