#!/usr/bin/env python3
"""check_beacon_coverage.py -- commit-time GoatCounter beacon-coverage gate.

Problem this guards against: docs/INSTRUMENTATION-SETUP.md's "Coverage rule"
(every user-facing *.html page carries exactly one data-goatcounter tag) was
prose only, with no enforcement. On 2026-08-20 the tag covered 16 of 26
user-facing pages -- the analytics install was green and working, and
structurally incapable of measuring pages nobody had wired. A coverage rule
with no enforcement decays at every branch merge; this script is the
enforcement.

SCOPE (population), stated with the pattern, not left implicit
----------------------------------------------------------------
The population is an EXPLICIT glob list (DEFAULT_TARGET_GLOBS below), never
an implicit directory walk -- imitating the DEFAULT_TARGET_GLOBS idiom in
scripts/check_proof_numbers.py. This means:
  - scripts/og-card.html is out of scope by omission (it is a generator
    template, never served to a visitor -- documented exclusion #1).
  - .claude/worktrees/** is out of scope by omission (throwaway worktrees,
    not the deployed site -- documented exclusion #2). An explicit glob list
    rooted at specific top-level names/patterns never reaches into that
    directory, so this exclusion falls out for free rather than needing a
    negative rule.
docs/INSTRUMENTATION-SETUP.md never states the population as a literal glob
list; this script's reading is "every *.html file actually served by the
site: the root-level pages plus articles/*.html and case-studies/*.html",
which is what the doc's own worked example (16 of 26, 26 = the population)
enumerates. If a new top-level *.html page is added outside articles/ or
case-studies/, it must be added to DEFAULT_TARGET_GLOBS by hand -- the same
trade-off check_proof_numbers.py already makes and already documents.

RULE
----
Exactly one data-goatcounter tag per in-scope page. Zero FAILs (missing
beacon -- the actual 2026-08-20 incident). Two FAILs (duplicate beacons
double-count pageviews, corrupting the analytics as surely as a missing one).

PRODUCER/CONSUMER PARITY
-------------------------
scoreboard.html is fully GENERATED by scripts/generate-scoreboard.mjs; its
beacon lives in that script's own <head> template, not only in the checked-in
output file. A check that scans only the output file goes GREEN while the
generator loses its beacon -- and the next `node
scripts/generate-scoreboard.mjs` run silently reverts the output back to
beacon-less. GENERATED_PAGES below names every such pair; both the output
file (scanned as part of DEFAULT_TARGET_GLOBS) AND the generator template are
checked, and either side losing its beacon fails the gate.

Exit codes mirror .githooks/pre-commit's existing check_proof_numbers.py
contract: 0 = clean, 2 = coverage violated (see printed FAIL lines for which
files and what was wrong), any other non-zero = a fault in the gate itself
(the hook must report that distinctly from a real verdict -- never let a
crash masquerade as "coverage disagrees").

Stdlib only. ASCII-only. Pure: no network, no subprocess.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

BEACON_ATTR_RE = re.compile(r"data-goatcounter\s*=")

# Population: every user-facing *.html page, as an explicit, greppable glob
# list -- never an implicit directory walk. See the module docstring's SCOPE
# section for the exclusions this omits (scripts/og-card.html,
# .claude/worktrees/**) and why the doc itself never states this as a literal
# glob. Mirrors DEFAULT_TARGET_GLOBS in scripts/check_proof_numbers.py.
DEFAULT_TARGET_GLOBS = [
    "404.html",
    "index.html",
    "managed-watch.html",
    "scoreboard.html",
    "articles/*.html",
    "case-studies/*.html",
]

# Producer/consumer parity pairs: {generated output file -> generator script
# that produces it}. Both sides are checked for exactly one beacon; either
# side missing or duplicating it fails the gate. See the module docstring's
# PRODUCER/CONSUMER PARITY section.
GENERATED_PAGES = {
    "scoreboard.html": "scripts/generate-scoreboard.mjs",
}

# Documented exclusions from docs/INSTRUMENTATION-SETUP.md's exclusion table.
# These are the ONLY *.html files allowed to exist outside DEFAULT_TARGET_GLOBS.
# Listing them POSITIVELY (rather than relying on omission) is what lets the
# orphan check below tell "deliberately excluded" apart from "nobody noticed".
EXCLUDED_HTML = [
    "scripts/og-card.html",   # generator template, never served to a visitor
]

# Directories that are not the deployed site at all. Unlike EXCLUDED_HTML these
# are not pages-with-a-reason, they are simply not the site.
NON_SITE_DIRS = (".claude", ".git", "drafts", "node_modules")


def find_unclassified_pages(
    root: Path,
    patterns: list[str],
    excluded: list[str] | None = None,
) -> list["Finding"]:
    """Fail on any *.html file that is neither in scope NOR explicitly excluded.

    WHY THIS EXISTS -- it closes the gate's own blind spot. DEFAULT_TARGET_GLOBS
    names three top-level pages LITERALLY (404/index/managed-watch/scoreboard),
    so without this check a newly added top-level page -- say pricing.html --
    would be out of scope BY OMISSION: the gate would print OK while an
    uninstrumented page shipped. Verified adversarially 2026-08-20 before this
    function existed: dropping a beacon-less pricing.html into the tree left the
    gate reporting "OK (26 page(s) checked)", exit 0.

    That is precisely the failure this whole gate was built to prevent. The
    16-of-26 incident happened because case-study pages landed on one branch
    while instrumentation landed on another and nothing reconciled them; a
    hardcoded list re-opens exactly that hole for root-level pages.

    docs/INSTRUMENTATION-SETUP.md's rule is "every user-facing .html page", not
    "the pages someone remembered to list". So every *.html under the site tree
    must be classified as either IN SCOPE (covered by a glob) or EXCLUDED (named
    in EXCLUDED_HTML with a reason) -- and an unclassified page is a FAIL that
    names the choice, rather than silence that hides it.

    An empty result and a flood are the same smell: a coverage checker that
    cannot see a file is not passing it, it is missing it.
    """
    excluded_rel = set(excluded if excluded is not None else EXCLUDED_HTML)
    in_scope = {p.resolve() for p in resolve_targets(root, patterns)}

    findings: list[Finding] = []
    for path in sorted(root.rglob("*.html")):
        if not path.is_file():
            continue
        try:
            rel = path.relative_to(root)
        except ValueError:  # pragma: no cover -- rglob cannot escape root
            continue
        if any(part in NON_SITE_DIRS for part in rel.parts):
            continue
        if rel.as_posix() in excluded_rel:
            continue
        if path.resolve() in in_scope:
            continue
        findings.append(Finding(path, 0, "unclassified"))
    return findings


class Finding:
    """One coverage violation: either a scanned page with the wrong beacon
    count, or a generator template with the wrong beacon count."""

    def __init__(self, path: Path, count: int, kind: str):
        self.path = path
        self.count = count
        # "missing" | "duplicate" | "missing-generator" | "unclassified"
        self.kind = kind

    def format(self) -> str:
        rel = self.path
        if self.kind == "unclassified":
            return (
                f"FAIL {rel}: this page is neither in DEFAULT_TARGET_GLOBS nor "
                f"in EXCLUDED_HTML, so the beacon rule silently skips it. Add it "
                f"to one or the other in scripts/check_beacon_coverage.py -- "
                f"being unlisted is not the same as being exempt"
            )
        if self.kind == "missing-generator":
            return (
                f"FAIL {rel}: generator template not found on disk -- the "
                f"producer/consumer beacon pairing is broken (see "
                f"GENERATED_PAGES in scripts/check_beacon_coverage.py)"
            )
        if self.kind == "missing":
            return f"FAIL {rel}: 0 data-goatcounter tags found (expected exactly 1)"
        return (
            f"FAIL {rel}: {self.count} data-goatcounter tags found "
            f"(expected exactly 1 -- a duplicate beacon double-counts pageviews)"
        )


def count_beacon_tags(text: str) -> int:
    return len(BEACON_ATTR_RE.findall(text))


def resolve_targets(root: Path, patterns: list[str]) -> list[Path]:
    """Resolve DEFAULT_TARGET_GLOBS (or caller-supplied patterns) against
    `root`. Explicit glob list, not a directory walk -- see module docstring.
    Mirrors check_proof_numbers.py's resolve_targets() exactly."""
    paths: list[Path] = []
    for pattern in patterns:
        paths.extend(sorted(root.glob(pattern)))
    seen = set()
    result = []
    for p in paths:
        if p.is_file() and p not in seen:
            seen.add(p)
            result.append(p)
    return result


def check_file(path: Path) -> Finding | None:
    """Check one page for exactly-one-beacon. Returns None (clean) or a
    Finding describing the violation."""
    text = path.read_text(encoding="utf-8", errors="replace")
    count = count_beacon_tags(text)
    if count == 0:
        return Finding(path, count, "missing")
    if count > 1:
        return Finding(path, count, "duplicate")
    return None


def check_generated_pairs(root: Path, pairs: dict[str, str]) -> list[Finding]:
    """Check the generator-template side of every producer/consumer pair.
    The output-file side is already covered by check_file() as part of the
    normal DEFAULT_TARGET_GLOBS scan (scoreboard.html is in that list); this
    function is what catches the generator losing its beacon while the
    (soon to be silently reverted) output file still carries one.

    A pair is only enforced when its OUTPUT file actually exists in this
    tree -- if the output page itself isn't present (e.g. a minimal test
    fixture, or a future repo restructure that drops it), there is nothing
    generated here for parity to protect, so the pair is skipped rather than
    demanding an unrelated generator script exist. Once the output file IS
    present, the generator must exist and carry exactly one beacon too --
    that pairing is the actual parity guarantee."""
    findings: list[Finding] = []
    for output_rel, generator_rel in pairs.items():
        output_path = root / output_rel
        if not output_path.is_file():
            continue
        generator_path = root / generator_rel
        if not generator_path.is_file():
            findings.append(Finding(generator_path, 0, "missing-generator"))
            continue
        text = generator_path.read_text(encoding="utf-8", errors="replace")
        count = count_beacon_tags(text)
        if count == 0:
            findings.append(Finding(generator_path, count, "missing"))
        elif count > 1:
            findings.append(Finding(generator_path, count, "duplicate"))
    return findings


def run(
    root: Path = REPO_ROOT,
    target_patterns: list[str] | None = None,
    generated_pairs: dict[str, str] | None = None,
) -> int:
    patterns = target_patterns if target_patterns is not None else DEFAULT_TARGET_GLOBS
    pairs = generated_pairs if generated_pairs is not None else GENERATED_PAGES

    targets = resolve_targets(root, patterns)

    findings: list[Finding] = []
    for path in targets:
        f = check_file(path)
        if f is not None:
            findings.append(f)
    findings.extend(check_generated_pairs(root, pairs))
    findings.extend(find_unclassified_pages(root, patterns))

    for finding in findings:
        print(finding.format())

    if findings:
        print(f"\ncheck_beacon_coverage: {len(findings)} FAIL")
        return 2

    print(
        f"check_beacon_coverage: OK ({len(targets)} page(s) checked, "
        f"{len(pairs)} generator pairing(s) checked)"
    )
    return 0


def main(argv: list[str]) -> int:
    try:
        return run()
    except Exception as exc:  # noqa: BLE001 -- fault in the gate itself, must not masquerade as a verdict
        print(f"check_beacon_coverage: FATAL -- {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
