#!/usr/bin/env python3
"""generate_self_audit_table.py -- regenerate the dogfood self-audit block.

Problem this fixes: articles/fleet-audit-methodology.html used to embed a
hand-typed, dated snapshot of mcp-security-scanner's `--self-audit` output
(which server is CLEAN, which has FINDINGS, per-server P1 counts, and a
short description of each P1 finding). That snapshot only reflects reality
at the moment someone typed it -- the next time any fleet server's audit
status changes (a finding gets fixed, a new fixture trips a detector), the
page silently goes stale with no gate to catch it. This is the same class
of bug as the proof-manifest.toml test-count drift that scripts/
check_proof_numbers.py exists to catch -- except this data isn't a single
number, so it needs its own generator rather than a citation-scan.

What this script does: actually invokes `mcp-scan --self-audit --json`
against the real fleet, in mcp-security-scanner's own checkout, and
rewrites the auto-generated region of articles/fleet-audit-methodology.html
(everything between the SELF-AUDIT-AUTOGEN:START/END HTML comments) from
the live result. It never hand-waves the numbers -- if the scan can't run,
it fails loudly and leaves the file untouched rather than guessing.

DO NOT hand-edit the region between the SELF-AUDIT-AUTOGEN markers in
articles/fleet-audit-methodology.html. Run this script instead, review the
diff, and commit.

Usage (from this repo's root):

    python scripts/generate_self_audit_table.py [--check]

Requires, same convention as mcp-security-scanner's own --self-audit:
  MCP_SCANNER_FLEET_ROOT   directory containing the fleet's MCP server repos
                            (e.g. C:\\Users\\you\\projects)
Optional:
  MCP_SCANNER_REPO         path to the mcp-security-scanner checkout. If
                            unset, defaults to a sibling directory of this
                            site repo (../mcp-security-scanner relative to
                            this repo's parent) -- the common local layout
                            where both repos live side by side. That default
                            is computed from this script's own location, not
                            hardcoded into any tracked file's contents, so it
                            carries no personal path into git history.

--check: don't write anything; exit 1 if the generated content would differ
from what's currently in the file (for a future CI/pre-commit wiring, not
enforced anywhere yet -- this is a manual-run tool today).

Stdlib only. ASCII-only output (mirrors check_proof_numbers.py's rail).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TARGET_FILE = REPO_ROOT / "articles" / "fleet-audit-methodology.html"

MARKER_START = "<!-- SELF-AUDIT-AUTOGEN:START -- regenerated by scripts/generate_self_audit_table.py; do not hand-edit, run the script instead -->"
MARKER_END = "<!-- SELF-AUDIT-AUTOGEN:END -->"

REGION_RE = re.compile(
    re.escape(MARKER_START) + r".*?" + re.escape(MARKER_END),
    re.DOTALL,
)

FLEET_ROOT_ENV_VAR = "MCP_SCANNER_FLEET_ROOT"
SCANNER_REPO_ENV_VAR = "MCP_SCANNER_REPO"

_NUM_WORDS = {
    0: "zero", 1: "one", 2: "two", 3: "three", 4: "four", 5: "five",
    6: "six", 7: "seven", 8: "eight", 9: "nine", 10: "ten",
}


def _word(n: int) -> str:
    return _NUM_WORDS.get(n, str(n))


def resolve_scanner_repo() -> Path:
    raw = os.environ.get(SCANNER_REPO_ENV_VAR)
    if raw:
        return Path(raw)
    # Sibling-directory default: this site repo and mcp-security-scanner
    # both live under the same parent in the operator's normal layout.
    return REPO_ROOT.parent / "mcp-security-scanner"


def run_self_audit_json(scanner_repo: Path) -> list[dict]:
    if not os.environ.get(FLEET_ROOT_ENV_VAR):
        raise RuntimeError(
            f"{FLEET_ROOT_ENV_VAR} is not set. This script (like mcp-scan "
            f"--self-audit itself) needs it to point at the directory "
            f"containing your fleet's MCP server repos, e.g.\n"
            f'  (PowerShell): $env:{FLEET_ROOT_ENV_VAR} = "C:\\Users\\you\\projects"\n'
            f"  (bash):        export {FLEET_ROOT_ENV_VAR}=/path/to/your/projects"
        )
    if not scanner_repo.is_dir() or not (scanner_repo / "mcp_scanner").is_dir():
        raise RuntimeError(
            f"mcp-security-scanner checkout not found at {scanner_repo}. Set "
            f"{SCANNER_REPO_ENV_VAR} to point at your local clone, e.g.\n"
            f'  (PowerShell): $env:{SCANNER_REPO_ENV_VAR} = "C:\\path\\to\\mcp-security-scanner"'
        )
    proc = subprocess.run(
        [sys.executable, "-m", "mcp_scanner.cli", "--self-audit", "--json"],
        cwd=str(scanner_repo),
        capture_output=True,
        text=True,
        timeout=180,
        env=os.environ.copy(),
    )
    if proc.returncode not in (0, 1):
        # 1 is the scanner's own --fail-on exit path; --self-audit here never
        # passes --fail-on so this shouldn't fire, but don't assume.
        raise RuntimeError(
            f"mcp-scan --self-audit --json exited {proc.returncode} in "
            f"{scanner_repo}.\nstdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"
        )
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"could not parse JSON from mcp-scan --self-audit --json output: {exc}\n"
            f"raw stdout:\n{proc.stdout}"
        ) from exc


def _short_name(target: str) -> str:
    return target.replace("\\", "/").rstrip("/").rsplit("/", 1)[-1]


def build_region(results: list[dict]) -> str:
    if not results:
        raise RuntimeError(
            "mcp-scan --self-audit --json returned an empty list -- no fleet "
            "servers were found under MCP_SCANNER_FLEET_ROOT. Refusing to "
            "generate a page claiming zero servers were audited."
        )

    rows = []
    for r in results:
        name = _short_name(r["target"])
        counts = r["counts_by_severity"]
        rows.append({
            "name": name,
            "clean": bool(r["clean_bill"]),
            "p0": counts.get("P0", 0),
            "p1": counts.get("P1", 0),
            "p1_titles": sorted({
                f["title"] for f in r["findings"] if f.get("severity") == "P1"
            }),
        })

    scan_dates = {r.get("scan_meta", {}).get("scan_date") for r in results}
    scan_dates.discard(None)
    scan_date = sorted(scan_dates)[-1] if scan_dates else "unknown-date"

    total = len(rows)
    clean_rows = [r for r in rows if r["clean"]]
    flagged_rows = [r for r in rows if not r["clean"]]
    p0_total = sum(r["p0"] for r in rows)

    # Headline clause (server counts + P0/P1 tally) is always wrapped in
    # <strong>, matching the original hand-written copy's emphasis. The
    # per-server detail after the em-dash (only present when something is
    # flagged) sits outside the <strong>.
    # 2026-08-19: "clean bill" was REMOVED from this copy on purpose. Measured
    # recall on third-party code is 0/69 (0/7 restricted to the classes this
    # tool implements), so a server returning nothing is SILENCE, not evidence
    # of safety -- see the recall paragraph emitted below. This block may only
    # describe what the scanner EMITTED; it may never characterise the security
    # of the targets. Do not reintroduce "clean bill", "trust claim", or
    # "strongest proof" here.
    if not flagged_rows:
        headline = (
            f"{_word(total)} of my own MCP servers scanned, P0={p0_total} "
            f"fleet-wide, no P0/P1 returned on any of them"
        )
        claim = f"<strong>{headline}.</strong>"
    else:
        headline = (
            f"{_word(total)} of my own MCP servers scanned, P0={p0_total} "
            f"fleet-wide, {_word(len(clean_rows))} returned nothing, "
            f"{_word(len(flagged_rows))} flagged"
        )
        parts = []
        for r in flagged_rows:
            desc = "; ".join(r["p1_titles"]) if r["p1_titles"] else "no P1 detail available"
            parts.append(f'<code>{r["name"]}</code> ({r["p1"]}x P1/LOW, {desc}, honestly reported)')
        if len(parts) == 1:
            joined = parts[0]
        elif len(parts) == 2:
            joined = f"{parts[0]} and {parts[1]}"
        else:
            joined = ", ".join(parts[:-1]) + f", and {parts[-1]}"
        claim = f"<strong>{headline}</strong> \u2014 {joined}. No other server carries a P0 or P1."

    pre_lines = []
    for r in rows:
        # "CLEAN" was replaced 2026-08-19: it asserts a security state this
        # tool's measured recall (0/69) cannot support. These labels describe
        # what the scanner EMITTED, nothing more.
        if r["clean"]:
            pre_lines.append(f'NO P0/P1  {r["name"]}')
        else:
            pre_lines.append(f'FLAGGED   {r["name"]:<14}P1={r["p1"]}')
    pre_body = "\n".join(pre_lines)

    lines = [
        MARKER_START,
        "        <p>",
        "          <code>--self-audit</code> points the scanner at the fleet of MCP servers it was built",
        "          alongside, locked by a real test in the suite (<code>tests/test_self_audit.py</code>) and",
        f"          reproducible yourself rather than a one-off demo run: {claim}",
        "        </p>",
        "        <p>",
        "          <strong>Read that as a regression gate, not a security result.</strong> Measured blind",
        "          against five third-party MCP servers on 2026-07-29, this scanner returned",
        "          <strong>0 true positives across 58 findings</strong> and <strong>recall 0/69</strong>",
        "          (<strong>0/7</strong> restricted to the three classes it implements). Recall fixes the",
        "          next day raised it to two findings that survive a hand audit — one of real-world",
        "          consequence — and pooled recall has not been re-scored since, so no current number is",
        "          claimed either way. A server that returns nothing here has produced <em>silence</em>,",
        "          not a clean bill. I pulled the paid audit tier the day that first measurement landed.",
        "          This table shows the self-audit runs in CI and that the report format is real; it is",
        "          not evidence that any server listed is secure.",
        "        </p>",
        "        <p>",
        f"          Live sample run ({scan_date} — regenerated by "
        "<code>scripts/generate_self_audit_table.py</code>, not hand-typed; re-run it "
        "and commit whenever the fleet changes. Per-server P2/ungraded counts still drift",
        "          run-to-run as detectors evolve and are deliberately not part of the headline",
        "          above, only the P0/P1 tally is):",
        "        </p>",
        '        <pre style="background:rgba(0,0,0,0.25); padding:14px 16px; border-radius:8px; overflow-x:auto; font-size:0.85em; line-height:1.5"><code>'
        + pre_body + "</code></pre>",
        "        " + MARKER_END,
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                         help="don't write; exit 1 if the file would change")
    args = parser.parse_args(argv)

    scanner_repo = resolve_scanner_repo()
    try:
        results = run_self_audit_json(scanner_repo)
        new_region = build_region(results)
    except RuntimeError as exc:
        print(f"generate_self_audit_table: FAILED -- {exc}", file=sys.stderr)
        return 2

    if not TARGET_FILE.is_file():
        print(f"generate_self_audit_table: FAILED -- {TARGET_FILE} not found", file=sys.stderr)
        return 2

    original = TARGET_FILE.read_text(encoding="utf-8")
    if not REGION_RE.search(original):
        print(
            f"generate_self_audit_table: FAILED -- could not find the "
            f"SELF-AUDIT-AUTOGEN:START/END marker region in {TARGET_FILE}. "
            f"Has the page been restructured? Re-add the markers by hand "
            f"once, then this script can maintain the region.",
            file=sys.stderr,
        )
        return 2

    updated = REGION_RE.sub(lambda _m: new_region, original, count=1)

    if updated == original:
        print("generate_self_audit_table: no change (already up to date).")
        return 0

    if args.check:
        print("generate_self_audit_table: STALE -- the self-audit region would change. "
              "Run without --check to regenerate.")
        return 1

    TARGET_FILE.write_text(updated, encoding="utf-8")
    print(f"generate_self_audit_table: updated {TARGET_FILE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
